# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qwu9mF3jpYdEaDUsaVAcXEVuI2S9wOnp
"""

import streamlit as st
from utils import agent
from datetime import datetime

st.set_page_config(page_title="🧠 Mental Health Q&A Agent", layout="centered")

# --- Header ---
st.markdown("## 💬 Ask Your Mental Health Assistant")
st.markdown("An AI-powered assistant to support your mental health questions using RAG + LLM")

# --- Input Box with Placeholder ---
user_question = st.text_input(
    "Ask a question:",
    placeholder="e.g. Why do I feel anxious before exams?"
)

# --- Session history setup ---
if "history" not in st.session_state:
    st.session_state.history = []

# --- Processing user input ---
if user_question:
    with st.spinner("🤖 Thinking..."):
        try:
            response = agent.run(user_question)
            # Save Q&A to session history
            st.session_state.history.append((user_question, response))

            # Display answer
            st.markdown("### 🧠 Response:")
            st.success(response)
            st.caption(f"Answered on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

        except Exception as e:
            st.error(f"An error occurred: {e}")

# --- Show Previous Q&A ---
if st.session_state.history:
    with st.expander("🕘 View Previous Questions"):
        for i, (q, a) in enumerate(reversed(st.session_state.history), 1):
            st.markdown(f"**Q{i}:** {q}")
            st.markdown(f"**A{i}:** {a}")
            st.markdown("---")